### ISSUE TITLE
building greens function for distances up to 1300 km

### ISSUE THREAD

**Issue by alirezaniki** [pyrocko/pyrocko#152]
Hi
i am trying to build a greens function using fomosto-qseis-2006 with this config : 
distance = 30 - 1300 km
depth =  1 - 25 km
sampling rate = 10 hz

but every time i tried it faced some error like : 
qseis end state non-zero = -9 (some thing like this !)
nr > nrmax
nbsjmax defined too small
and so on ..
----------------------------
what i have to do on this?
can anyone help me on this?

**Comment by emolch** [comment]
Hi alirezaniki,
I think your setup should work. I use the current qseis.2006a from here: 
https://gitext.gfz-potsdam.de/fomosto-backends/fomosto-qseis

I did
```
fomosto init qseis.2006a mytest
```
Then changed the extent and sampling rate in `mytest/config`:
```
...
sample_rate: 10.                                                                
...
source_depth_min: 1000.0                                                        
source_depth_max: 25000.0                                                       
source_depth_delta: 1000.0                                                      
distance_min: 30000.0                                                           
distance_max: 1300000.0                                                         
distance_delta: 1000.0
```
Then ran
```
cd mytest
fomosto ttt
fomosto build
```
and it seems to work - no qseis errors so far. Maybe try with a fresh install of qseis.

It might take a while to compute though...

Best wishes
Sebastian

**Comment by alirezaniki** [comment]
Thanks Dear Sebastian
it sounds its working for me too
great job 
i think my problem was because of my old qseis.2006 
thanks a lot
