### ISSUE TITLE
cannot run setup.py install

### ISSUE THREAD

**Issue by xiansch** [pyrocko/pyrocko#161]
Hi all, when I try to install pyrocko 0.2, this happens:

/Users/schu3/anaconda/envs/earthquakes/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:681:82: error: 
      expected value in expression
  ...&& (NPY_API_VERSION <= NPY_NO_DEPRECATED_API))
                                                 ^
/Users/schu3/anaconda/envs/earthquakes/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1378:81: error: 
      expected value in expression
  ...&& (NPY_API_VERSION <= NPY_NO_DEPRECATED_API))
                                                 ^
/Users/schu3/anaconda/envs/earthquakes/lib/python2.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1727:82: error: 
      expected value in expression
  ...&& (NPY_API_VERSION <= NPY_NO_DEPRECATED_API))
                                                 ^
pyrocko/mseed_ext.c:254:41: warning: incompatible pointer types passing 'int *'
      to parameter of type 'int64_t *' (aka 'long long *')
      [-Wincompatible-pointer-types]
                                     1, &psamples, 1, 0, NULL);
                                        ^~~~~~~~~
./libmseed/libmseed.h:569:20: note: passing argument to parameter
      'packedsamples' here
                               int64_t *packedsamples, flag flush, flag verbose,
                                        ^
1 warning and 3 errors generated.
error: command 'gcc' failed with exit status 1

**Comment by emolch** [comment]
Hi Xiansch,

last change in Pyrocko v0.2 has been done in 2012, so please use the current version. 

Current practice is that we try to always keep Pyrocko's master branch stable and only occasionally tag a specific commit with a version number, e.g. when certain heavy development branches get merged into master. Small features, bugfixes and new modules are continuously integrated into master, once stable. This revolving release model is always open for discussion of course. So far it worked ok for us, I think - opinions? @miili, @HerrMuellerluedenscheid

Best wishes
Sebastian

**Comment by HerrMuellerluedenscheid** [comment]
Hi Xiansch and others,

I agree with Sebastian's reply. However, funny coincidence is that this is the second time within a week I see a question related to version 0.2 installation. Maybe we should clarify a little which is the version we consider as stable. The description of both versions on pyrocko.org leaves space for interpretation, due to words like 'development' and 'experimental', isn't it?

**Comment by emolch** [comment]
This part of the documentation has already been removed in the new version of the web page, so this should be solved as soon as we have the new web page online...

**Comment by xiansch** [comment]
I have installed the version directly from this github, however when I try to run Snuffler, the module 'avl' is not found?  I cannot find this package anywhere.

**Comment by emolch** [comment]
Did you do the `sudo easy_install pyavl` (or similar) during the installation procedure?

See also here: http://pyrocko.org/v0.3/install_quick.html
