### ISSUE TITLE
problem with default strore in local engine

### ISSUE THREAD

**Issue by simondaout** [pyrocko/pyrocko#166]
Hi,

I have noticed an error with the default store in local engine when I am following the tutorial example. 

If I define my engine as follow:
engine = LocalEngine(store_superdirs=['/data1/work/gf_store/'])
store_id = 'tibet'
I got the error: NoDefaultStoreSet
Even if  engine.get_store_ids() returns me all the correct stores, ie: ['crust2_dd', 'inter', 'menyuan', 'tibet']

The solution I found is to define my engine as follow:
engine = LocalEngine(store_superdirs=['/data1/work/gf_store/'],default_store_id=store_id)
In this case, everything is working well.

Simon

**Comment by emolch** [comment]
I think the possibility to have a default store was maybe not a very good idea. Maybe we should even remove this possibility to avoid future confusion.

Anyway, the above error should only occur when trying to calculate synthetics for a target with `store_id=None`. It should not be necessary to set the default_store_id on the engine. Could you please check where exactly the error occurs and e.g. print the target before it goes into `process()`?

**Comment by braunfuss** [comment]
The error is reproducible if no default store dir is set for me.
Can be circumvented if in the beginning of document os.environ["GF_STORE_SUPERDIRS "] = "path"
is set (or globally set the right way).
Maybe there should be also enabled also a direct store call like: engine = LocalEngine(store=['fullpath/store_id']) ?

**Comment by miili** [comment]
Look like we'll stay with `default_store`; tutorial has been updated.
