### ISSUE TITLE
How to combine two greens functions?

### ISSUE THREAD

**Issue by alirezaniki** [pyrocko/pyrocko#173]
Hi everybody
I have two greens functions which i want to combine them into one greens function. both of them are equal in epicenteral distances. the depth range for case 1 is 1-35 and for case 2 is 35-70.
is it possible to combine these two GFs? is it can be done using redeploy command?
many thanks.

**Comment by emolch** [comment]
Hi,

Yes, this can be done with redeploy. Here's roughly how it is done:

http://pyrocko.org/v0.3/apps/fomosto/tutorial.html#how-to-combine-or-split-green-s-function-stores

In short (to merge stores `a` and `b` into `c`):
```
$ fomosto init redeploy a c
$ # edit c/config to cover combined depth range
$ fomosto redeploy a c
$ fomosto redeploy b c
```
