### ISSUE TITLE
random traces are empty 

### ISSUE THREAD

**Issue by hvasbath** [pyrocko/pyrocko#175]
After sucessfully building stores. Very rarely happened now for 2 stores out of 1520 created stores ...
Is it possible to let only specific traces be filled/repaired? So far I saw the IBLOCK argument but that doesnt agree with the trace index that one can find using fomosto check ...

**Comment by hvasbath** [comment]
Not even rebuilding the store fixes it. The same traces are empty again ... must be something setup specific?

**Comment by hvasbath** [comment]
The config file, cant get markdown to work ...
--- !pf.ConfigTypeA
id: BORG_ak135_1.000Hz_47
modelling_code_id: qseis.2006a
earthmodel_1d: |2
      0.             5.516          3.009          2.6           50.            50.
      3.037          5.516          3.009          2.6           50.            50.
      3.037          5.675          3.032          2.6          600.           400.
      5.046          5.675          3.032          2.6          600.           400.
      5.046          5.845          3.252          2.7          600.           400.
     10.4            5.845          3.252          2.7         1400.           600.
     10.4            6.084          3.472          2.75        1400.           600.
     15.67           6.084          3.472          2.75        1400.           600.
     15.67           6.29           3.576          2.8         1400.           600.
     20.54           6.29           3.576          2.8         1400.           600.
     20.54           6.971          3.996          3.2         1283.           600.
     35.5            6.971          3.996          3.2         1283.           600.
  mantle
     35.5            7.003          4.059          3.58        1449.           600.
     42.22           7.903          4.558          3.5         1445.           600.
     68.95           7.99           4.594          3.5         1001.           400.
     79.03           8.024          4.472          3.5         1008.           417.6
     79.03           8.109          4.526          3.502        182.            75.6
    121.             8.114          4.536          3.427        182.6           76.06
    121.             8.184          4.574          3.427        182.6           76.06
    169.4            8.309          4.582          3.371        188.7           76.55
    211.3            8.348          4.543          3.324        201.            79.4
    211.3            8.424          4.585          3.323        338.2          133.7
    314.4            8.752          4.745          3.401        353.6          138.7
    409.4            8.826          4.757          3.506        377.5          146.5
    409.4            9.374          5.088          3.929        414.1          162.7
    661.2           10.21           5.619          3.918        428.5          172.9
    661.2           10.79           5.965          4.24        1349.           549.5
    764.            11.07           6.215          4.359       1276.           537.1
    849.1           11.21           6.272          4.463       1263.           527.3
   1038.            11.52           6.407          4.616       1230.           506.9
   1227.            11.81           6.527          4.71        1198.           488.
   1416.            12.08           6.636          4.812       1168.           470.4
   1605.            12.33           6.735          4.909       1141.           454.4
   1795.            12.55           6.827          5.004       1111.           437.7
   1984.            12.78           6.913          5.096       1065.           415.6
   2173.            13.             6.997          5.186       1037.           400.6
   2362.            13.21           7.079          5.273        995.4          381.2
   2551.            13.43           7.162          5.357        968.1          367.3
   2740.            13.65           7.248          5.439        932.5          350.6
   2740.            13.65           7.248          5.693        722.7          271.7
   2790.            13.65           7.259          5.72         726.9          274.
   2839.            13.66           7.27           5.746        725.1          274.
   2892.            13.66           7.282          5.772        723.1          274.
  outer-core
   2892.             7.972          0.             9.928          5.782E+04      0.
earthmodel_receiver_1d: |2
      0.             1.888          0.8942         1.9           50.            50.
      0.1551         1.888          0.8942         1.9           50.            50.
      0.1551         4.838          2.416          2.6          600.           400.
      5.543          4.838          2.416          2.6          600.           400.
      5.543          6.787          3.751          2.9         1471.           600.
     11.85           6.787          3.751          2.9         1471.           600.
     11.85           6.807          3.732          3.05        1491.           600.
     23.81           6.807          3.732          3.05        1491.           600.
  mantle
     23.81           7.953          4.439          3.625        955.3          396.8
     82.85           7.957          4.434          3.5         1008.           417.6
     82.85           8.112          4.527          3.502        182.            75.6
    121.             8.116          4.536          3.431        182.6           76.03
    121.             8.184          4.574          3.427        182.6           76.06
    169.4            8.309          4.582          3.371        188.7           76.55
sample_rate: 1.0
component_scheme: elastic10
tabulated_phases:
- !pf.TPDef
  id: any_P
  definition: p,P,p\,P\
- !pf.TPDef
  id: any_S
  definition: s,S,s\,S\
ncomponents: 10
receiver_depth: 0.0
source_depth_min: 0.0
source_depth_max: 40000.0
source_depth_delta: 1000.0
distance_min: 5455958.028542664
distance_max: 5595958.028542664
distance_delta: 1000.0

**Comment by hvasbath** [comment]
This always happened for a specific station with specific velocity models. However, I cannot identify whats the problem with the velocity models in these cases...

**Comment by emolch** [comment]
It can happen, that for certain (distance, source-depth) cake fails because of rounding errors. This leads to holes in the travel-time tables which are needed when defining the cut range. We could try to improve cake, but I already tried that some time ago and failed to find a simple fix. Another option would be to fill the hole in the travel-time table. Third option would be to patch fomosto.qseis to use neighboring time ranges when the t interpolation does not give a result. Workaround would now be to add a fallback in the time window and cutting options in extra/qseis. E.g. a constant velocity which is used when phase does not yield a result.

**Comment by HerrMuellerluedenscheid** [comment]
#204 should help to identify such problems much faster.

**Comment by hvasbath** [comment]
tackled here: https://github.com/pyrocko/pyrocko/pull/233
