### ISSUE TITLE
fomosto GOMP:parallel

### ISSUE THREAD

**Issue by blazvicic** [pyrocko/pyrocko#185]
Hi!

I have problem running fomosto after installing pyrocko.

I have anaconda3 running on my system (ubuntu 16.4). 
I created separate env with:
conda create -n python2 python=2.7 anaconda

then i enter this new env with :
source activate python2

then i followed the instruction on how to install pyrocko.
when all is over, i tried with snuffler, no problem there, it works.
but when i tried fomosto, i get this error:

> (python2) blaz@blazU:~$ fomosto 
> Traceback (most recent call last):
>   File "/home/blaz/anaconda3/envs/python2/bin/fomosto", line 10, in <module>
>     from pyrocko import util, trace, gf, cake, io, gui_util
>   File "/home/blaz/anaconda3/envs/python2/lib/python2.7/site-packages/pyrocko/gf/__init__.py", line 23, in <module>
>     from pyrocko.gf.store import *  # noqa
>   File "/home/blaz/anaconda3/envs/python2/lib/python2.7/site-packages/pyrocko/gf/store.py", line 18, in <module>
>     from pyrocko.gf import store_ext
> ImportError: /home/blaz/anaconda3/envs/python2/lib/python2.7/site-packages/pyrocko/gf/store_ext.so: undefined symbol: GOMP_parallel

what should i do?
thanks!

**Comment by miili** [comment]
It appears there is an issue linking OpenMP libraries on your system.

https://software.intel.com/en-us/articles/gcc-49-openmp-code-cannot-be-linked-with-intel-openmp-runtime

Do you have an Intel C compiler installed along with GCC?

Unfortunately I cannot reproduce this behaviour, as a workaround you may look into the `setup.py` and have `_check_for_openmp()` return `False`. However you will work on a single CPU then.

**Comment by blazvicic** [comment]
this are compilers installed on my system:

> ii  g++                                        4:5.3.1-1ubuntu1                              amd64        GNU C++ compiler
> ii  g++-5                                      5.4.0-6ubuntu1 16.04.4                        amd64        GNU C++ compiler
> ii  gcc                                        4:5.3.1-1ubuntu1                              amd64        GNU C compiler
> ii  gcc-5                                      5.4.0-6ubuntu1 16.04.4                        amd64        GNU C compiler
> ii  gfortran                                   4:5.3.1-1ubuntu1                              amd64        GNU Fortran 95 compiler
> ii  gfortran-5                                 5.4.0-6ubuntu1 16.04.4                        amd64        GNU Fortran compiler
> ii  hardening-includes                         2.7ubuntu2                                    all          Makefile for enabling compiler flags for security hardening
> ii  libllvm3.8:amd64                           1:3.8-2ubuntu4                                amd64        Modular compiler and toolchain technologies, runtime library
> ii  libllvm3.8:i386                            1:3.8-2ubuntu4                                i386         Modular compiler and toolchain technologies, runtime library
> ii  libxkbcommon0:amd64                        0.5.0-1ubuntu2                                amd64        library interface to the XKB compiler - shared library

i will try with your proposal, but i would really like to use all the cores :)

**Comment by miili** [comment]
You may double check that `libgomp1` is installed on your system and Anaconda https://anaconda.org/intel/openmp

Further see this suggestion at http://stackoverflow.com/a/39046588/2387835.

**Comment by blazvicic** [comment]
Funny, Fomosto now works without any problem, so I decided to try also Grond. and with Grond I get similar error:

> Traceback (most recent call last):
>   File "/usr/local/bin/grond", line 11, in <module>
>     from pyrocko.gf import Range
>   File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/__init__.py", line 23, in <module>
>     from pyrocko.gf.store import *  # noqa
>   File "/usr/local/lib/python2.7/dist-packages/pyrocko/gf/store.py", line 18, in <module>
>     from pyrocko.gf import store_ext
> ImportError: /usr/local/lib/python2.7/dist-packages/pyrocko/gf/store_ext.so: undefined symbol: GOMP_parallel

any idea?
thanks!

**Comment by emolch** [comment]
Looks like you have two installations of Pyrocko. One under `/usr/local` and and anotherone under Anaconda. Grond seems to use the /usr/local installation while Fomosto uses the anaconda installation, I guess. The former one seems to be broken. Try to reinstall Grond with the Anaconda Python interpreter and remove everything under `/usr/local/lib/python2.7/dist-packages/pyrocko` to avoid future problems.

**Comment by blazvicic** [comment]
Ok, I deleted everything in that folder (pyrocko and grond subfolders)

then I reinstalled Pyrocko with:

> source activate pyrocko (my py2.7 env)
and install as it is written here
http://pyrocko.org/current/install_anaconda2.html

then I clone grond and install with (still under pyrocko env):

> git clone https://gitext.gfz-potsdam.de/heimann/grond.git
> cd grond
> sudo python setup.py install

The error persists

**Comment by emolch** [comment]
Ah, I guess it's the 'sudo' in the 'sudo python setup.py install'. This would call the system Python rather than the Anaconda Python.

**Comment by blazvicic** [comment]
yes! this is it, thanks!
Will keep in mind this next time, I did't know sudo chooses system python!

**Comment by blazvicic** [comment]
btw, is there some example how to prepare all the data?
thnx

**Comment by emolch** [comment]
Sorry, could you please illuminate the last question with a bit more context? Maybe consider to open a new issue on this one, to make it easier to keep track and not mix things up.

Thanks and best wishes
Sebastian
