### ISSUE TITLE
store_ext.error

### ISSUE THREAD

**Issue by blazvicic** [pyrocko/pyrocko#187]
Dear all!

Now that I managed to install pyrocko without problems, I am trying to run examples from the website.
The synthetic seismogram example runs without problem (gf_forward_example1.py), but I get an error while trying to run Calculate spatial surface displacement from a local store (gf_forward_example2.py).

This is what I get:

> Traceback (most recent call last):
>   File "gf_forward_example2.py", line 57, in <module>
>     result = engine.process(rect_source, [satellite_target])
>   File "/home/blaz/anaconda3/envs/pyrocko/lib/python2.7/site-packages/pyrocko/gf/seismosizer.py", line 2804, in process
>     nthreads=nprocs):
>   File "/home/blaz/anaconda3/envs/pyrocko/lib/python2.7/site-packages/pyrocko/gf/seismosizer.py", line 2385, in process_static
>     source, target, components, nthreads)
>   File "/home/blaz/anaconda3/envs/pyrocko/lib/python2.7/site-packages/pyrocko/gf/seismosizer.py", line 2662, in base_statics
>     nthreads)
>   File "/home/blaz/anaconda3/envs/pyrocko/lib/python2.7/site-packages/pyrocko/gf/store.py", line 1750, in statics
>     nthreads)
> store_ext.error: INDEX_OUT_OF_BOUNDS

I get the same error in example 1 if I change DCsource to RectangularSource.

What does this error mean?
Thanks!
Blaž

**Comment by hvasbath** [comment]
Your GreensFunction store does not contain the necessary Greens Functions, meaning that your source is partially outside of your GF store grid / and or that your observation points are as well. So you have to extend the size of your GF store. max_depth max_distance ...

**Comment by blazvicic** [comment]
Ok, thanks, for the example2 i set crust2_dd, now I changed back to "gf_abruzzo_nearfield_vmod_Ameri" and it works... So basicaly, I just need to recreate a GF store as explained in the examples and I should be good to go?

Thank you very much!
