### ISSUE TITLE
FOMOSTO: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO

### ISSUE THREAD

**Issue by blazvicic** [pyrocko/pyrocko#192]
Dear all...

I am getting this error while running fomosto build for some blocks:

> WARNING:fomosto.qseis:qseis emitted something via stderr:
> 
> Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG IEEE_DIVIDE_BY_ZERO

This are my config:

> --- !pf.ConfigTypeA
> id: est4a
> modelling_code_id: qseis.2006a
> earthmodel_1d: |2
>       0.             4.8            2.7            2.45          50.            50.
>       0.5            5.6            3.2            2.60          50.            50.
>       2.             5.8            3.3            2.65         200.           200.
>       4.             6.2            3.5            2.70         200.           200.
>       6.             5.7            3.3            2.80         200.           200.
>      14.             6.2            3.5            2.90         200.           200.
>      16.             6.5            3.7            3.10         200.           200.
>      26.             7.0            3.7            3.35         600.           400.
>      37.             7.5            4.0            3.35         600.           400.
>   mantle
>      37.             8.0            4.2            3.35        1350.           600.
>      40.             8.1            4.3            3.35        1350.           600.
>      43.             8.1            4.5            3.35        1350.           600.
>      43.             8.1            4.5            3.35        1350.           600.
>      80.             8.0            4.5            3.50        1350.           600.
>     120.             8.0            4.5            3.42        1350.           600.
>     165.             8.2            4.5            3.37        1350.           600.
>     210.             8.3            4.5            3.32        1350.           600.
>     300.             8.6            4.7            3.40        1350.           600.
>     410.             9.0            4.9            3.50        1350.           600.
>     660.            10.2            5.6            3.92        1350.           600.
> sample_rate: 2.0
> component_scheme: elastic10
> tabulated_phases:
> - !pf.TPDef
>   id: any_P
>   definition: p,P,p\,P\
> - !pf.TPDef
>   id: any_S
>   definition: s,S,s\,S\
> - !pf.TPDef
>   id: slowest
>   definition: '0.8'
> ncomponents: 10
> receiver_depth: 0.0
> source_depth_min: 1000.0
> source_depth_max: 30000.0
> source_depth_delta: 250.0
> distance_min: 10000.0
> distance_max: 200000.0
> distance_delta: 250.0

and qseis files:

> --- !pf.QSeisConfig
> qseis_version: 2006a
> time_region: [any_P-30, last(slowest|any_S)+50]
> cut: [any_P-30, last(slowest|any_S)+50]
> fade: [any_P-30, any_P-10, last(slowest|any_S)+30, last(slowest|any_S)+50]
> relevel_with_fade_in: true
> sw_algorithm: 0
> slowness_window: [0.0, 0.0, 0.0, 0.0]
> wavenumber_sampling: 2.5
> aliasing_suppression_factor: 0.10000000000000001
> filter_surface_effects: 0
> filter_shallow_paths: 0
> filter_shallow_paths_depth: 0.0
> sw_flat_earth_transform: 1
> gradient_resolution_vp: 0.0
> gradient_resolution_vs: 0.0
> gradient_resolution_density: 0.0
> wavelet_duration_samples: 0.001
> wavelet_type: 2

What is the cause for this warning?

Thanks!

**Comment by hvasbath** [comment]
I think you have the same issue as mentioned here:
https://github.com/pyrocko/fomosto-psgrn-pscmp/issues/3

You can try following the suggestions in there ...

**Comment by blazvicic** [comment]
thanks, but no luck...

I tried with gfortran-6 and gfortran-7, recompiled the fomosto, but still getting the same error. Which compiler should I try? Last time it was said to not use Intel fortran compiler. any advice?

thanks

**Comment by hvasbath** [comment]
Sorry, I dont know anything else but trying different compiler versions ...
I am using gfortran version 4.6.3 and 4.8.4 on another machine. With both of them it works ...

**Comment by blazvicic** [comment]
i installed 4.8 and rerun compilation with
sudo CC="gcc-4.8" ./configure
sudo CC="gcc-4.8" make

still the same problem :/

thanks anyway, I hope we get somewhere with this.

**Comment by hvasbath** [comment]
ah did you try?: 
F77=gfortran ./configure
make
make install

**Comment by blazvicic** [comment]
same...

but I saw this when runing make...

> bessj.f:13:72:
> 
>        if(n.lt.2)pause 'bad argument n in bessj'

> Making all in src
> make[1]: Entering directory '/home/blaz/Software/Pyrocko/fomosto-qseis-2006a/src'
> f77  -g -O2 -c -o qsmatrix0.o qsmatrix0.f
> f77  -g -O2 -c -o bessj0.o bessj0.f
> f77  -g -O2 -c -o bessj1.o bessj1.f
> f77  -g -O2 -c -o bessj.o bessj.f
> bessj.f:13:72:
> 
>        if(n.lt.2)pause 'bad argument n in bessj'
>                                                                         1
> Warning: Deleted feature: PAUSE statement at (1)
> f77  -g -O2 -c -o caxcb.o caxcb.f
> f77  -g -O2 -c -o cdgemp.o cdgemp.f
> f77  -g -O2 -c -o cmemcpy.o cmemcpy.f
> f77  -g -O2 -c -o four1.o four1.f
> f77  -g -O2 -c -o qsam2ve.o qsam2ve.f
> f77  -g -O2 -c -o qsbsj.o qsbsj.f
> f77  -g -O2 -c -o qsfftinv.o qsfftinv.f
> f77  -g -O2 -c -o qsgetinp.o qsgetinp.f
> f77  -g -O2 -c -o qshksh.o qshksh.f
> f77  -g -O2 -c -o qskern.o qskern.f
> f77  -g -O2 -c -o qslayer.o qslayer.f
> f77  -g -O2 -c -o qsmain.o qsmain.f
> f77  -g -O2 -c -o qsmultis.o qsmultis.f
> f77  -g -O2 -c -o qspsv.o qspsv.f
> f77  -g -O2 -c -o qsqmodel.o qsqmodel.f
> f77  -g -O2 -c -o qssh.o qssh.f
> f77  -g -O2 -c -o qssource.o qssource.f
> f77  -g -O2 -c -o qssublay.o qssublay.f
> f77  -g -O2 -c -o qsve2am.o qsve2am.f
> f77  -g -O2 -c -o qswavelet.o qswavelet.f
> f77  -g -O2 -c -o qswaveno.o qswaveno.f
> f77  -g -O2 -c -o qswvint.o qswvint.f
> f77  -g -O2 -c -o taper.o taper.f
> f77  -g -O2 -c -o wavelet.o wavelet.f
> f77  -g -O2 -c -o skip_comments.o skip_comments.f
> f77  -g -O2   -o fomosto_qseis2006a qsmatrix0.o bessj0.o bessj1.o bessj.o caxcb.o cdgemp.o cmemcpy.o four1.o qsam2ve.o qsbsj.o qsfftinv.o qsgetinp.o qshksh.o qskern.o qslayer.o qsmain.o qsmultis.o qspsv.o qsqmodel.o qssh.o qssource.o qssublay.o qsve2am.o qswavelet.o qswaveno.o qswvint.o taper.o wavelet.o skip_comments.o  
> make[1]: Leaving directory '/home/blaz/Software/Pyrocko/fomosto-qseis-2006a/src'
> make[1]: Entering directory '/home/blaz/Software/Pyrocko/fomosto-qseis-2006a'
> make[1]: Nothing to be done for 'all-am'.
> make[1]: Leaving directory '/home/blaz/Software/Pyrocko/fomosto-qseis-2006a'

**Comment by hvasbath** [comment]
no but thats wrong now it is using f77 compiler instead of gfortran ...

**Comment by blazvicic** [comment]
ah, I had to run F77=gfortran make

but anyway, it is the same.

> Making all in src
> make[1]: Entering directory '/home/blaz/Software/Pyrocko/fomosto-qseis-2006a/src'
> gfortran  -g -O2 -c -o qsmatrix0.o qsmatrix0.f
> gfortran  -g -O2 -c -o bessj0.o bessj0.f
> gfortran  -g -O2 -c -o bessj1.o bessj1.f
> gfortran  -g -O2 -c -o bessj.o bessj.f
> bessj.f:13:72:
> 
>        if(n.lt.2)pause 'bad argument n in bessj'
>                                                                         1
> Warning: Deleted feature: PAUSE statement at (1)
>   .
>   .
>   .

during make
and same warning when i run fomosto build

**Comment by hvasbath** [comment]
I get this pause and warning as well, that doesnt seem to be the problem....

**Comment by blazvicic** [comment]
ah, gfortran 4.6 is not producing any warnings (but maybe it is just not catching them?)

anyway:
on ubuntu:
sudo apt-get install gfortran-4.6

and then:
sudo F77=gfortran-4.6 ./configure
sudo F77=gfortran-4.6 make
sudo F77=gfortran-4.6 make install

thanks!

**Comment by miili** [comment]
Solved

**Comment by blazvicic** [comment]
could be that old gfortran is really just not catching the error?

I built the GF using gfortran 4.6 without problems, but when I start calculating synthetics, I hit some problems...

When calculating double couple source everything seems fine, but when I start to calculate extended source, I get error

> pyrocko.gf.store.StoreError: EMPTY_RECORD in store /home/blaz/Software/Pyrocko/stores/est4a10

I think GF db should be ok - i set from 0 to 150km in distance and depth from 0 to 30. for the extended source my parameters are:
			    depth=16000,
			    width=10000,
			    length=18000,

any idea?

**Comment by emolch** [comment]
Hi!
These seem to be two separate problems. I tracked the origin of the floating point warnings down to a part of the qseis code where some internal parameters, like step size and ranges for the integration of slowness are tuned based on the earth model with some ray-tracing. I asked Rongjiang about it but did not get an answer so far. At the moment, I think the warnings can be ignored because they do not seem to affect the result (I have seen and ignored them in different setups already for a while). However, we should double-check and fix the flaw in the algorithm to not produce warnings.

The EMPTY_RECORDS error has a different origin. It looks like the `any_P` phase has a hole in the domain you are computing.

![figure_1](https://user-images.githubusercontent.com/124167/27121395-6aef49f4-50e7-11e7-80e7-41b58a131e49.png)

We can consider this a bug of fomosto to not create a warning/error when this happens. I reopen in a different issue.

**Comment by blazvicic** [comment]
interesting, thanks!
any idea where the hole is coming from (the config is in the first post)?

**Comment by emolch** [comment]
To fix the problem, you can add a fallback to another phase in the cutting definition when the `any_P` is not existent at some (depth, distance). Or simply change to using a constant velocity for the onset cutting.

**Comment by emolch** [comment]
this is why the hole occurs:

![rays](https://user-images.githubusercontent.com/124167/27121667-89d41704-50e8-11e7-9524-98479d69b54d.png)

**Comment by blazvicic** [comment]
thanks!
