### ISSUE TITLE
Migrate to Python >= 3.5

### ISSUE THREAD

**Issue by vvug** [pyrocko/pyrocko#221]
It's really time to. ObsPy already supports it.

**Comment by emolch** [comment]
Pyrocko unofficially already supports Python3

```
git fetch origin
git checkout python3-testing
sudo python3 setup.py install
```

There are still some little problems here and there, but most things work smoothly :-)

Cheers!
Sebastian

**Comment by emolch** [comment]
Feedback about experiences with the `python3-testing` branch is of course very welcome...

**Comment by emolch** [comment]
Completed since v2017.11
