### ISSUE TITLE
Make fomosto build aware of travel-time-table holes

### ISSUE THREAD

**Issue by emolch** [pyrocko/pyrocko#228]

**Comment by emolch** [comment]
Almost everyone using fomosto runs into this problem, so it is important to fix.

**Comment by HerrMuellerluedenscheid** [comment]
#204 is dedicated to that issue. It's ready but requires to revisit some GF tests. Some contain holes... I'll finish that soon after next major update.

**Comment by HerrMuellerluedenscheid** [comment]
I'm closing this issue since #233 has solved that issue by adding more verbosity and additional checks for ttt holes.
