### ISSUE TITLE
Picking procedure in Snuffler

### ISSUE THREAD

**Issue by grajh** [pyrocko/pyrocko#230]
Hello! 

Regarding the Snuffler's picking tool. Would it be possible for the time window picking tool to show middle pick (estimated pick) of the symmetrical uncertainty window. It would even be better if the user would be able to first pick the estimated arrival time of the phase and then determine the uncertainty window. In that case user would first activate the picking mode, then push the left mouse button down to determine the estimated arrival and while still holding the left mouse button also determine the uncertainty window by moving mouse up or down.

Thank you for your consideration.

**Comment by emolch** [comment]
Thanks for the suggestion! Should be easy to implement. Click-and-hold is already used for marking time intervals, but we could use e.g. ctrl-click-and-hold to create a marker with symmetrical uncertainties and give it a new visual appearance. I remember some discussion on such a feature some years ago with @HerrMuellerluedenscheid - maybe he has already created something in this direction?

**Comment by emolch** [comment]
ok, why not? f65db6a175a886e023c4affdb62e12e3cb6f7bf2 (and in d853e38509a8b5f2a6a203d1ce47459e18e2674c for Py 2/3)

* 'G' will now zoom tightly to selection. If nothing is selected or if the selection has zero duration, it will zoom approximately to the level where traces become visible.

* 'g' should work as before: jump to selection possibly with zoom to trace visibility. Preserves the zoom level if traces are already visible. See full dataset if nothing is selected.

**Comment by neatcoder** [comment]
Doesn't seem to work. I am on Python 2.7 with install inside Anaconda. I just updated and installed over the previous installation. Have also manually checked if the files were updated during the process and everything seems to be ok.

**Comment by emolch** [comment]
Most likely a problem with dual install (anaconda/system) python.

Could you please run these to aid debugging?

* `which python`
* `which snuffler`

**Comment by neatcoder** [comment]
[In] which snuffler
[Out] /home/gregor/anaconda2/bin/snuffler
[In] which python
[Out] /home/gregor/anaconda2/bin/python

**Comment by emolch** [comment]
and this?
```
python
>>> import pyrocko
>>> print pyrocko.long_version
```

**Comment by neatcoder** [comment]
pyrocko-0.3-c6f4b10be8965ed6f48b549f726c2e3893f4c25b-2017-10-22_16:13:25

Looks like installation is still from yesterday, eventhough I made a complete upgrade. Any idea how to do a complete reinstall? Maybe this is the issue.

**Comment by emolch** [comment]
Just a guess: could it be that you used `sudo python setup.py install` when upgrading? With anaconda you should run it without sudo, otherwise it will use the system python again.

**Comment by neatcoder** [comment]
My bad, that did it. Thank you very much!

**Comment by emolch** [comment]
At the moment we are busy finishing the Python 2/3 support but as soon as this is done, we will have a look at it!

**Comment by neatcoder** [comment]
Great. Thanks!

**Comment by HerrMuellerluedenscheid** [comment]
Hi,
checkout 4c4dc396d2fc7ead9a4f0234b26a3599cdbc0b88 [branch: marker_with_uncertainty]. It's just the beginning but you can select markers, press CTRL and drag the mouse down to set (and see) the Marker.uncertainty attribute. Next step is to implement import/ export. Now, that we started improving the marker, we should think about some more aspects: Should we add more functionality? What else is missing? Should markers with uncertainty be a different/special type of marker?

**Comment by neatcoder** [comment]
Wow, that was fast. Thank you!

While setting the uncertainty it would be great that a time span of the uncertainty window would show up interactively somewhere. I think it would be wise to set a category of the uncertainty marker by default to also be a phase marker, since I don't see any other use for it. Maybe in the future it could also be a "maximum amplitude" marker, I don't know.

Simple option for import/export would be to just export the uncertainty marker as a time instant value with added column of dt (delta time or so called uncertainty). This way the uncertainty phase marker would be recognized automatically.

I was also thinking about setting a phase polarity, but this can already be set in the Snuffler configuration file without a problem just by changing a name of the phase marker for the chosen function key. Since I am already talking about the configuration file. Is it possible to also change some other parameters in it (e. g. page skip time interval)? What about setting the default values of seismogram viewing options (main menu) in the configuration file, so for example the scaling option would always be the chosen one when opening and closing Snuffler?

**Comment by HerrMuellerluedenscheid** [comment]
Events also have an uncertainty. So, now that I thought about it a little, I think the uncertainty is a good think to have on each marker.

Snuffling settings should be in there, too! You are right. We should add this feature soon. If you like you can try that out yourself. Take a look at the "visible_length" that can be set in the config file. Most of what would have to be done to include the other options is copy paste. Don't hesitate to ask in case you get stuck.

I like the idea of adding polarities as special types of phases in the config file. On the other hand, this could be also a dedicated set of keys, as it is quite common to assign them. How about up and down arrows when a marker is selected? They are not used at the moment.

@emolch would we want to give away the arrow keys for this purpose?

**Comment by laisnrodrigues** [comment]
Hello!

Can someone help me?
I'm using the snuffler to do picks and I need change the X axis hour:min:sec for seconds. I can't find the file to make this modification. Please, help me.

**Comment by emolch** [comment]
@laisnrodrigues how exactly would you like this feature to look like? Should it be an offset time to the active event? If you just want to measure some times, you can click and hold and see the duration of the selection in seconds in the status line at the bottom of the window.

**Comment by laisnrodrigues** [comment]
Hello!! Thanks for attention.
I would like the x axis show me the time in seconds. When I open the snuffler the time starts on 0 seconds and the P phase on 700 seconds, for example.

**Comment by HerrMuellerluedenscheid** [comment]
Hi @laisnrodrigues 

What would be the reference in that case? Which sample should match  `time=0`? The time axis in snuffler's main window should display the global (best UTC) time.
For you specific wish I think it's a better idea to write an independent plotting snuffling. That way you can plot your data the way you like. Event better: You can set `time=0` to whatever position in time you desire. Have a look into the [user contributed snufflings](https://github.com/pyrocko/contrib-snufflings) and the `plot_traces.py` snuffling in particular to see how this can be achieved.

**Comment by HerrMuellerluedenscheid** [comment]
By the way: You can always shift your data to any location in time. But this is rather a matter of preprcessing. Checkout [this example](https://pyrocko.org/docs/current/library/examples/trace_handling.html#time-shifting-a-trace) to see how shifting traces can be done in a script. This should allow you to set any sample to `t=0`.
