### ISSUE TITLE
anaconda3 install

### ISSUE THREAD

**Issue by bvicic** [pyrocko/pyrocko#238]
dear all

I tried installing pyrocko with anaconda installation on virtual Ubuntu 16.03
looks like all went OK, but when i call snuffler or fomosto, this is the msg i get:

> Traceback (most recent call last):
>   File "/home/blaz/anaconda3/bin/snuffler", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
>   File "/home/blaz/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2985, in <module>
>   File "/home/blaz/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2971, in _call_aside
>   File "/home/blaz/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
>   File "/home/blaz/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 660, in _build_master
>   File "/home/blaz/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 968, in require
>   File "/home/blaz/anaconda3/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 854, in resolve
> pkg_resources.DistributionNotFound: The 'pyrocko==2017.11' distribution was not found and is required by the application

reinstaling gives back this:

> Fetching package metadata ...............
> Solving package specifications: .
> 
> # All requested packages already installed.
> # packages in environment at /home/blaz/anaconda3:
> #
> pyrocko                   2017.11              he7e82d4_0    pyrocko

any idea?
thanks!

**Comment by rantanplan77** [comment]
Same error here, on a fresh conda environment:

```(pyrocko) luckyluke@wildwest:~$ snuffler
Traceback (most recent call last):
  File "/home/luckyluke/miniconda3/envs/pyrocko/bin/snuffler", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/luckyluke/miniconda3/envs/pyrocko/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/home/luckyluke/miniconda3/envs/pyrocko/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/home/luckyluke/miniconda3/envs/pyrocko/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/luckyluke/miniconda3/envs/pyrocko/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/home/luckyluke/miniconda3/envs/pyrocko/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/luckyluke/miniconda3/envs/pyrocko/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyrocko==2018.1.29' distribution was not found and is required by the application```

**Comment by miili** [comment]
Pyrocko Anaconda packages are online at https://anaconda.org/pyrocko/pyrocko

to install use:
```
conda install -c pyrocko pyrocko 
```
