### ISSUE TITLE
fomosto startup hits problem in store.py on the import store_ext, missing a lib GOMP_4.0 

### ISSUE THREAD

**Issue by iceseismic** [pyrocko/pyrocko#239]
Installed pyrocko using anaconda2,  (using 'conda install -c pyrocko pyrocko')  but when I try "fomosto --help"  or "fomoso init --help"   it fails in module load_entry_point('pyrocko==2017.11.22', 'console_scripts', 'fomosto')()  tracking down to some issue with  store_ext, where it can't find  GOMP_4.0 : 

![image](https://user-images.githubusercontent.com/831424/33188269-7cf96ff8-d0fd-11e7-95ff-91bf0fc88ea2.png)

ImportError: /home/stephen/anaconda2/lib/python2.7/site-packages/pyrocko/gf/../../../../libgomp.so.1: version 'GOMP_4.0' not found (required by /home/stephen/anaconda2/lib/python2.7/site-packages/pyrocko/gf/store_ext.so ) 

When I do 'conda info' it gives me a user-agent as follows:  conda/4.3.29 requests/2.14.2 Cpython/2.7.13 Linux/3.3.1-3.fc16.x86_64 Fedora/16 glibc/2.14.90

Any suggestions ??  I don't have any root-privilege on this machine; just local

**Comment by HerrMuellerluedenscheid** [comment]
Hi @iceseismic, I did some research on that issue and found a similar problem reported here https://github.com/jupyter/docker-stacks/issues/177. It might stem from the gcc version used by conda. Could you try to install conda's gcc and see if that solves the problem?

    conda install -y gcc

Let me know if that has any effect.

**Comment by iceseismic** [comment]
Thanks very much for the suggestion. In the end I installed anaconda3 instead of anaconda2, with a clean start, and "fomosto init --help" now runs without any issue. I suspect I had all sorts of conflicts before that.
