### ISSUE TITLE
Waveforms from Seiscomp Data Structure (SDS)

### ISSUE THREAD

**Issue by jmsolanof** [pyrocko/pyrocko#246]
Hello,

I've been looking for a tool/library/script to read waveforms from a SDS. This is to read these waveforms choosing channels, time windows, etc.

But I couldnot find such thing.

So I ask: Is there such thing?

Thank you all.

Juan Manuel

**Comment by hvasbath** [comment]
If it is only about plotting and browsing, you may use snuffler:
```
snuffler filename.sds
```
Otherwise if you want to manipulate data you can use a pile:
```
from pyrocko import pile
p = pile.make_pile(['filename.sds'])
```
then you can iterate over the traces and do whatever you want then on the traces with:
```
for trace in p.iter_traces():
    print trace
```

**Comment by jmsolanof** [comment]
Hi hvasbath,

I'm not sure I understand you.
The thing is that I need to read data from SDS which is not a file but a folder with sub folders with this structure:
`<SDSdir>/Year/NET/STA/CHAN.TYPE/NET.STA.LOC.CHAN.TYPE.YEAR.DAY`
Where:
```
SDSdir 	:  arbitrary base directory
YEAR 	:  4 digit year
NET 	:  Network code/identifier, up to 8 characters, no spaces
STA 	:  Station code/identifier, up to 8 characters, no spaces
CHAN 	:  Channel code/identifier, up to 8 characters, no spaces
TYPE 	:  1 characters indicating the data type, recommended types are:
	        'D' - Waveform data
	        'E' - Detection data
	        'L' - Log data
	        'T' - Timing data
	        'C' - Calibration data
	        'R' - Response data
	        'O' - Opaque data
LOC 	:  Location identifier, up to 8 characters, no spaces
DAY 	:  3 digit day of year, padded with zeros
```
As you can see, there are day files into folders for every channel for every station for every network and for every year. That's the way seiscomp saves the data.

I want to be able to read data choosing channels and dates from this structure. But I can't find a tool.

On the other hand, are there files named like `filename.sds` ?

Thank you and anyone who can help me.

Juan Manuel

**Comment by miili** [comment]
Hi Juan,

check out the `Pile`. It acts as a mediator for large datasets

https://pyrocko.org/docs/current/library/examples/dataset_management.html
https://pyrocko.org/docs/current/library/reference/pile.html

Best,

Marius

**Comment by hvasbath** [comment]
Hi Juan,

as Marius mentioned, you can also simply give a directory instead of a file to the pile:
```
test_pile = pile.make_pile('/local/SDSdir')
```
Cheers!
