### ISSUE TITLE
snuffler not displaying traces

### ISSUE THREAD

**Issue by hvasbath** [pyrocko/pyrocko#267]
I have few traces that snuffler is simply not drawing for whatever reason. But if I plot them matplotlib and inspect the values they are reasonable. The timing is also not 0 ;) .
Shall I send someone the traces? @emolch , @HerrMuellerluedenscheid , @miili

**Comment by emolch** [comment]
Are there maybe some NaNs within?

**Comment by hvasbath** [comment]
I think the problem was that I hacked the channel definition of the traces by setting it without using set_channel. Then this resulted in a conflict with the nslc_id and snuffler doesnt draw it. But by properly using set_channel() it worked fine. Still I have to double check. But thats something for next week. Thanks!

**Comment by hvasbath** [comment]
Yes that was indeed the issue together with the location and set_location indeed. Closing.
