### ISSUE TITLE
How to save phase markers from snuffler into text file?

### ISSUE THREAD

**Issue by DianKusumawati** [pyrocko/pyrocko#281]
Hello there,
I'm new in using snuffler. However, I can not figure it out, how to save phase markers from snuffler interactive GUI into a text file. I tried to open the 'table listing markers' by pressing 'm', but I only end up in saving them in pdf (by print table). 

![image](https://user-images.githubusercontent.com/25811011/41669793-d4b841aa-74dc-11e8-8c44-89105aa69fb5.png)

Could anyone give guidance/ clue, about saving phase markers into text file, please? Any comment will be appreciated. I apologize if my question is a bit naive. 

Thank you.

**Comment by grajh** [comment]
Hello!

Open the main menu by right clicking on main seismogram viewing panel and choose "Save markers..." option. Markers are saved to ASCII file.

**Comment by DianKusumawati** [comment]
Ok thank youu

**Comment by hvasbath** [comment]
Question answered, closing.
