### ISSUE TITLE
jackseis network replacement re

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [pyrocko/pyrocko#284]
replacing empty network codes with something else doesn't work. E.g.

    jackseis --replace-network=//X/

should replace empty N with X.

It should be solved with something similar to this (but it's buggy too).

```
+++ b/src/apps/jackseis.py
@@ -304,7 +304,7 @@ def main(args=None):
             ('channel', options.rename_channel)]:
 
         for patrep in rename_k:
-            m = re.match(r'/([^/]+)/([^/]*)/', patrep)
+            m = re.match(r'/([^/]*)/([^/]*)/', patrep)
             if not m:
                 die('invalid argument to --rename-%s. '
                     'Expected format is /PATTERN/REPLACEMENT/' % k)
```

**Comment by miili** [comment]
RegEx `/^/NM/` matches an empty network field.

**Comment by HerrMuellerluedenscheid** [comment]
Thanks!

**Comment by HerrMuellerluedenscheid** [comment]
Nevertheless, shouldn't we make `jackseis --replace-network=//X/` work without knowing about regex? The other way works fine: `jackseis --replace-network=/X//` replaces 'X' with an empty string. I found this a little confusing I have to admit.
