### ISSUE TITLE
Issue in accessing gf database

### ISSUE THREAD

**Issue by IamSomak** [pyrocko/pyrocko#292]
Whenever I'm trying to run rapidinv code using a code such as : 

**./rapidinv config/20170424-3.7.inp**

it shows the following error:

**Initializing
Read input file, check and prepare inversion parameters
Prepare inversion directory, choose stations, prepare data
Taper applied
copied data from data/20170424-3.7/prepared
sh: 1: gfdb_info: not found
Traceback (most recent call last):
  File "./rapidinv", line 7739, in <module>
    assignSpacing(inv_param)
  File "./rapidinv", line 160, in assignSpacing
    val=str(max(dx,dz))
UnboundLocalError: local variable 'dx' referenced before assignment**

But I'm sure the crust2_re model files exist in the gfdb folder. Can you please tell me the possible cause of this problem?

**Comment by HerrMuellerluedenscheid** [comment]
Hi,

can you make sure that kiwi tools are properly installed. Looks like e.g. `gfdb_info` is not available. Please run

    gfdb_info
 
If it says something like 'command not found', you have to install [kiwi_tools](https://github.com/emolch/kiwi/wiki/Installation), first.

**Comment by IamSomak** [comment]
I tried re-installing the kiwi tools but when I'm going for the 'make' command, it gives me the following error:

...............
**gfdb_io_hdf.f90:(.text+0x349a): undefined reference to `__h5d_MOD_h5dclose_f'
collect2: error: ld returned 1 exit status
Makefile:164: recipe for target 'minimizer' failed
make: *** [minimizer] Error 1**

How to overcome this problem?

**Comment by HerrMuellerluedenscheid** [comment]
Looks like something is odd with your HDF5 installation. How did you install HDF5? Did you follow the instructions given on the kiwi homepage?

**Comment by IamSomak** [comment]
I did check with the HDF5 installation (as given in kiwi homepage) and found nothing wrong with it . But the problem still persists.

**Comment by IamSomak** [comment]
Hi Marius,

I tried installing it on a different system. After installing the prerequisites, when I run the rapidown program, it gives the following error:
**Traceback (most recent call last):
  File "./rapidown", line 18, in <module>
    from pyrocko import trace, util, io, cake, catalog, automap, pile, model
  File "/usr/local/lib/python2.7/dist-packages/pyrocko/trace.py", line 8, in <module>
    from builtins import zip
ImportError: No module named builtins**

Is this due to some missing files in the program itself or in the python?

**Comment by miili** [comment]
Hi IamSomiak,

install the package `future`:
On Debian based distros
```sh
sudo apt-get install python-future
```
or with pip
```sh
sudo pip install future
```

**Comment by IamSomak** [comment]
Thanks miili,

I guess the thing worked for rapidown, but for rapidinv, I'm stuck with the same problem as before:

**./rapidinv config/20170424-3.7.inp
Initializing
Read input file, check and prepare inversion parameters
Prepare inversion directory, choose stations, prepare data
Taper applied
copied data from data/20170424-3.7/prepared
gfdb_info: gfdb: failed to open file: gfdb/crust2_re/db.index
STOP 1
Traceback (most recent call last):
  File "./rapidinv", line 7739, in <module>
    assignSpacing(inv_param)
  File "./rapidinv", line 160, in assignSpacing
    val=str(max(dx,dz))
UnboundLocalError: local variable 'dx' referenced before assignment**

**Comment by IamSomak** [comment]
Hello everyone,

While trying the rapidinv code, I am repeatedly facing the error:
**Initializing
Read input file, check and prepare inversion parameters
Prepare inversion directory, choose stations, prepare data
Taper applied
copied data from data/20170206-5.9/prepared
radius 0 set to  1000.0
Calling minimizer result/20170206-5.9/minimizer.inp.dist
1 result/20170206-5.9/minimizer.inp.dist result/20170206-5.9/minimizer.out.dist
2 minimizer < result/20170206-5.9/minimizer.inp.dist > result/20170206-5.9/minimizer.out.dist
Fortran runtime error: Zero length string(s) passed to getenv.
Traceback (most recent call last):
  File "./rapidinv", line 7740, in <module>
    prepStations(inv_param,traces)
  File "./rapidinv", line 789, in prepStations
    f = open(fdistazitmp,'r')
IOError: [Errno 2] No such file or directory: 'result/20170206-5.9/distazi.dat.tmp'**

I can understand its unable to make the **distazi.dat.tmp** file, which is hindering the process. Can anyone tell me the reason for this issue and how to solve it?

**Comment by moscardo** [comment]
It seems that for some reasons there are no stations selected.

Try running in your work directory the following command:
minimizer < result/20170206-5.9/minimizer.inp.dist

This reads a station file (first command in result/20170206-5.9/minimizer.inp.dist)
and prepare the missing distazi file, containing distances and azimuths of those stations respect
to the epicenter.
It can be that the original station file is corrupted

**Comment by IamSomak** [comment]
Hello moscardo,

I tried the command, but it gave the same error:

**minimizer < result/20170206-5.9/minimizer.inp.dist
Fortran runtime error: Zero length string(s) passed to getenv.**

In case of my station file being corrupted, how do I build a stationxml file?
My station coordinates are written in a .txt file in the format:
<network_name>.<station_name>. <Latitude> <Longitude> <Depth> 0
KU.KHAT. 28.939 79.982 156 0

**Comment by IamSomak** [comment]
Currently, I am working with the following stationxml file (attached). Is there something wrong about it?

[india_stationxml.txt](https://github.com/pyrocko/pyrocko/files/2297014/india_stationxml.txt)

**Comment by moscardo** [comment]
Rapidinv/Kiwi work with a station ascii file as input, as the one 
I sent.Simone-- Dr. Simone CescaSection 2.1Physics of Earthquakes and VolcanoesTel.: +49 
(0)331/288-28794Fax: +49 (0)331/288-1204Email: simone.cesca@gfz-potsdam.de___________________________________Helmholtz-Zentrum 
PotsdamDeutsches GeoForschungsZentrum GFZStiftung des öff. Rechts Land BrandenburgTelegrafenberg, 14473 PotsdamOn Fri, 17 Aug 2018 
04:30:09 -0700 Somak <notifications@github.com> wrote:> Currently, I am working with the following stationxml >file 
(attached). Is there something wrong about it?> > [india_stationxml.txt](https://github.com/pyrocko/pyrocko/files/2297014/india_stationxml.txt)> 
> > -- > You are receiving this because you commented.> Reply to this email directly or view it on GitHub:> 
https://github.com/pyrocko/pyrocko/issues/292#issuecomment-413837260

**Comment by IamSomak** [comment]
Hey moscardo,

Sorry for the delay in reply. I an sending you the station file that is being generated by running the rapidinv program. Also, the contents of minimizer.inp.dist is as follows:

**set_receivers result/20170424-3.7/stations.txt.tmp
set_source_location 29.683 81.211 1493046269
output_distances result/20170424-3.7/distazi.dat.tmp**

As you can see, the problem exists in the creation of the distazi.dat.tmp file.

[stations.txt](https://github.com/pyrocko/pyrocko/files/2305164/stations.txt)

**Comment by IamSomak** [comment]
Thanks everyone. I figured it out. Another question I have is if I am using seismograms originally recording  at different  sampling rates (instrument of same make and frequency range) what possible changes are necessary  to run rapidinv on the data. I have matched their sampling rates and made changes to their network names, etc and generated the station file accordingly.

**Comment by HerrMuellerluedenscheid** [comment]
Hi @IamSomak 

You have to resample the data to match the sampling rate of the green's function database if I remember correctly. I think that rapidinv does not resample the data on it's own, does it? Checkout[ this pyrocko example ](https://pyrocko.org/docs/current/library/examples/trace_handling.html#resampling-a-trace)  to see how this can be done in a script. Alternatively, you can also use [jackseis](https://pyrocko.org/docs/current/apps/jackseis/) to achieve the same thing.
In general, please discuss issues separately to avoid lengthy discussions. Just open a new issue if you have another question.
Best regards

Marius

**Comment by moscardo** [comment]
I conform. With Kiwi/rapidinv you need to ensure same sampling of 
data and Green's functionsSimone-- Dr. Simone CescaSection 2.1Physics of Earthquakes and VolcanoesTel.: +49 
(0)331/288-28794Fax: +49 (0)331/288-1204Email: simone.cesca@gfz-potsdam.de___________________________________Helmholtz-Zentrum 
PotsdamDeutsches GeoForschungsZentrum GFZStiftung des öff. Rechts Land BrandenburgTelegrafenberg, 14473 PotsdamOn Tue, 26 Mar 2019 
10:32:28 +0000 (UTC) Marius Kriegerowski <notifications@github.com> wrote:> Hi @IamSomak > > You have to resample the 
data to match the sampling rate >of the green's function database if I remember correctly. >I think that rapidinv does not resample the 
data on it's >own, does it? Checkout[ this pyrocko example >](https://pyrocko.org/docs/current/library/examples/trace_handling.html#resampling-a-trace) 
> to see how this can be done in a script. Alternatively, >you can also use >[jackseis](https://pyrocko.org/docs/current/apps/jackseis/) 
>to achieve the same thing.> In general, please discuss issues separately to avoid >lengthy discussions. Just open a new issue if 
you have >another question.> Best regards> > Marius> > -- > You are receiving this because you 
commented.> Reply to this email directly or view it on GitHub:> https://github.com/pyrocko/pyrocko/issues/292#issuecomment-476565128
