### ISSUE TITLE
Jackseis wishlist

### ISSUE THREAD

**Issue by john-robert** [pyrocko/pyrocko#293]
Add the feature that one can state the number of characters used in the output template. For example,` %j` allows for Julian days, however, its format will have no leading zeros which can be painful. I'd imagine it like:
`%03j` will lead to  **004**, instead of **4**. Same applies perhaps to other template options. Cheers!

**Comment by emolch** [comment]
I would propose to simply change the output of `%j` and `%(julianday)s` to always be of format `%03i`. Times and dates are always zero-padded anyway, so this would be more consistent.
