### ISSUE TITLE
Grond: problem running synthetic test

### ISSUE THREAD

**Issue by shicks-seismo** [pyrocko/pyrocko#296]
Hi,
I am trying to get Grond installed. I just installed the latest version of Pyrocko using anaconda and installed the latest version of Grond. I am running with Python3 on OSX.
I am trying some of the Quickstart examples from https://pyrocko.org/grond/docs/current/quickstart/index.html#a-synthetic-test

However, when I run `grond scenario --targets=waveforms my_first_project`, I get the following error:

> (pyrocko) NOCS04167J-2:test_runs sph1r17$ grond scenario --targets=waveforms my_first_project --force
> grond:grond.scenario       - INFO     - Adding WaveformObservation
> grond:grond.scenario       - INFO     - Building scenario...
> grond:grond.scenario       - INFO     - Overwriting directory my_first_project.
> grond:grond.scenario       - INFO     - Creating scenario...
> Traceback (most recent call last):
>   File "/Users/sph1r17/anaconda/envs/pyrocko/bin/grond", line 11, in <module>
>     load_entry_point('grond==1.0', 'console_scripts', 'grond')()
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/apps/grond.py", line 161, in main
>     globals()['command_' + d2u(command)](args)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/apps/grond.py", line 425, in command_scenario
>     scenario.build(force=options.force, interactive=True)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/scenario.py", line 167, in build
>     self.create_scenario(interactive=interactive)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/scenario.py", line 110, in create_scenario
>     scenario.ensure_gfstores(
> AttributeError: 'ScenarioGenerator' object has no attribute 'ensure_gfstores'

**Comment by emolch** [comment]
The Pyrocko version on anaconda is a bit outdated at the moment - sorry for that. We will update it. If you can't wait, you can update Pyrocko master branch from source.

**Comment by shicks-seismo** [comment]
Thanks a lot, Sebastian! That seems fixed for now.
