### ISSUE TITLE
Water layer for Green's functions

### ISSUE THREAD

**Issue by shicks-seismo** [pyrocko/pyrocko#297]
Hi, more of a general question than an issue:

I am looking create regional Green's functions for an ocean bottom seismometer network - so I am wondering whether how robust Fomosto / Qseis is when you incorporate a water layer and put the receivers at depth in this layer? Has it been used for similar cases before?

**Comment by hvasbath** [comment]
I have accidentally used it this way, because I was not aware of water layers in crust 2. With receivers floating on the water. So I think this should be no problem, with receivers on the ocean bottom.

**Comment by emolch** [comment]
Yes this works! For a [`ConfigTypeA`](https://pyrocko.org/docs/current/library/reference/gf.html#pyrocko.gf.meta.ConfigTypeA) store, just set the [`receiver_depth`](https://pyrocko.org/docs/current/library/reference/gf.html#pyrocko.gf.meta.ConfigTypeA.receiver_depth) parameter in the GF config to match the water depth. Or place the receivers a little bit below the interface, I am not sure if there are rounding issues.

**Comment by shicks-seismo** [comment]
Thanks, and is it okay to have the S-velocity in the water layer = 0.00 km/s, or does it need to be nominally very small (e.g. 0.01 km/s) to ensure there are no numerical problems.

**Comment by emolch** [comment]
Setting S-velocity to zero is fine.

**Comment by shicks-seismo** [comment]
Actually, setting Vs = 0.00 does give the following error:

>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/cake.py", line 1230, in potint_coefs
>     c1c2 = c1/c2
> ZeroDivisionError: float division by zero

Here is my layered earth model:

> earthmodel_1d: |2
>       0.             1.45           0.0            1.02           5.782E+04      0.
>       3.93           1.45           1.1            1.02           5.782E+04      0
>       3.93           1.75           0.34           1.82        1350.           600.
>       4.02           1.75           0.34           1.82        1350.           600.
>       4.02           5.00           2.70           2.55        1350.           600.
>       4.72           5.00           2.70           2.55        1350.           600.
>       4.72           6.50           3.70           2.85        1350.           600.
>       6.25           6.50           3.70           2.85        1350.           600.
>       6.25           7.10           4.05           3.05        1350.           600.
>      10.97           7.10           4.05           3.05        1350.           600.
>   mantle
>      10.97           7.91           4.4            3.26        964.3           400.4
>      80.             8.04           4.481          3.5         1008.           417.6
>      80.             8.045          4.49           3.502        182.            75.6
>     120.             8.05           4.5            3.427        182.6           76.06
>     120.             8.05           4.5            3.427        182.6           76.06
>     165.             8.175          4.509          3.371        188.7           76.55
>     210.             8.301          4.518          3.324        201.            79.4
>     210.             8.3            4.519          3.323        338.2          133.7
>     300.             8.628          4.679          3.401        353.6          138.7
>     410.             9.03           4.87           3.506        377.5          146.5
>     410.             9.36           5.08           3.929        414.1          162.7
>     660.            10.2            5.611          3.918        428.5          172.9
>     660.            10.79           5.965          4.24        1349.           549.5

Changing Vs from 0.00 to 0.01 removes this error.
