### ISSUE TITLE
Issue with DoubleDCProblem

### ISSUE THREAD

**Issue by shicks-seismo** [pyrocko/pyrocko#298]
Hi, I've successfully run a CMTproblem with good results. Now I'd like to try a DoubleDCProblem using the same data and Green's functions. I have updated the config file with the correct parameters, but I run into this error when checking the config and/or running Grond for the optimisation:

> (pyrocko) NOCS04167J-2:M7mainshock sph1r17$ ./1_check_config.sh
> Traceback (most recent call last):
>   File "/Users/sph1r17/anaconda/envs/pyrocko/bin/grond", line 11, in <module>
>     load_entry_point('grond==1.0', 'console_scripts', 'grond')()
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/apps/grond.py", line 161, in main
>     globals()['command_' + d2u(command)](args)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/apps/grond.py", line 547, in command_check
>     env = Environment(args)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/environment.py", line 56, in __init__
>     self.set_selected_event_names(args[1:])
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/environment.py", line 120, in set_selected_event_names
>     event_names = self.get_available_event_names()
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/environment.py", line 95, in get_available_event_names
>     return self.get_config().get_event_names()
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/environment.py", line 90, in get_config
>     self._config = read_config(self._config_path)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/config.py", line 137, in read_config
>     config = guts.load(filename=path)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 189, in g
>     retval = f(*args, **kwargs)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 1815, in load
>     return _load(*args, **kwargs)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 1405, in _load
>     return yaml.load(stream=stream, Loader=Loader)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
>     return loader.get_single_data()
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/yaml/constructor.py", line 37, in get_single_data
>     return self.construct_document(node)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/yaml/constructor.py", line 41, in construct_document
>     data = self.construct_object(node)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/yaml/constructor.py", line 88, in construct_object
>     data = constructor(self, tag_suffix, node)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 1438, in multi_constructor
>     o.validate(regularize=True, depth=1)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 775, in validate
>     self.T.instance.validate(self, regularize, depth)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 488, in validate
>     val = validator.validate_children(val, regularize, depth)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 500, in validate_children
>     newpropval = prop.validate(propval, regularize, depth-1)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 468, in validate
>     val = self.regularize_extra(val)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/guts.py", line 493, in regularize_extra
>     return self.cls(val)
> TypeError: __init__() takes 1 positional argument but 2 were given

My config file is attached is that helps you find the problem.

Thanks in advance!
[config.txt](https://github.com/pyrocko/pyrocko/files/2353523/config.txt)

**Comment by emolch** [comment]
In the config, please replace `!grond.DoubleDCProblem` with `!grond.DoubleDCProblemConfig` and `name` with `name_template`.

Thanks for pointing to this issue, in the docs, there was a copy-and-paste error (`CMTProblemConfig`), should be fixed now.

I have not used this type of source recently, so could be that there are other issues ahead - don't hesitate to post them here. I would also be interested if it succeeds for your data, in my (few) tests, the double-dc usually was quite unstable...

**Comment by shicks-seismo** [comment]
Thanks a lot! I have used ISOLA (http://seismo.geology.upatras.gr/isola/) before for these kinds of double-source problems, so I am intrigued to see what Grond can do in a more probabilistic sense.

However, I find that I get a new error:

> (pyrocko) NOCS04167J-2:tmp sph1r17$ vi config/config.gronf.yaml
> (pyrocko) NOCS04167J-2:tmp sph1r17$ ./1_check_config.sh
> grond:grond.core           - INFO     - problem: cmt_e20160829.043000
> grond:grond.core           - INFO     - number of target families: 1
> grond:grond.core           - INFO     - number of targets (total): 60
> grond:grond.core           - INFO     - number of targets (selected): 60
> Traceback (most recent call last):
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gf/store.py", line 1890, in seismogram
>     interpolation, nthreads)
> pyrocko.gf.store_ext.StoreExtError: INDEX_OUT_OF_BOUNDS
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/sph1r17/anaconda/envs/pyrocko/bin/grond", line 11, in <module>
>     load_entry_point('grond==1.0', 'console_scripts', 'grond')()
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/apps/grond.py", line 161, in main
>     globals()['command_' + d2u(command)](args)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/apps/grond.py", line 559, in command_check
>     n_random_synthetics=options.n_random_synthetics)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/core.py", line 306, in check
>     results = problem.evaluate(x)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/grond/problems/base.py", line 479, in evaluate
>     resp = engine.process(source, modelling_targets_unique)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gf/seismosizer.py", line 3093, in process
>     nthreads=nthreads):
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gf/seismosizer.py", line 2639, in process_dynamic
>     source, target, components, dsource_cache, nthreads)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gf/seismosizer.py", line 2936, in base_seismogram
>     nthreads=nthreads)
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gf/store.py", line 1893, in seismogram
>     raise meta.OutOfBounds()
> pyrocko.gf.meta.OutOfBounds: out of bounds
> --- !pf.OutOfBoundsContext

> With the debug printing out this source configuration:
> source: !pf.DoubleDCSource
>   lat: -0.04928
>   lon: -17.87936
>   north_shift: -28716.451796896377
>   east_shift: -5731.180274051661
>   elevation: 0.0
>   depth: 29704.315873837222
>   name: e20160829.043000
>   time: 2016-08-29 04:30:17.057314
>   stf: !pf.HalfSinusoidSTF
>     duration: 0.0
>     anchor: 0.0
>   stf_mode: post
>   magnitude: 7.277270235342044
>   strike1: 169.05672873409657
>   dip1: 36.680867878619765
>   azimuth: 82.27033511540071
>   rake1: -121.47530036608481
>   strike2: 41.17466427948042
>   dip2: 22.252237783331637
>   rake2: 120.57665051469354
>   delta_time: 2.69330462830424
>   delta_depth: 3938.4642558070673
>   distance: 648344.3199583016
>   mix: 0.41699402698506993
>   stf1: !pf.HalfSinusoidSTF
>     duration: 16.900607071939927
>     anchor: 0.0
>   stf2: !pf.HalfSinusoidSTF
>     duration: 5.419442384107099
>     anchor: 0.0
> target: !grond.WaveformMisfitTarget
>   lat: -1.6703
>   lon: -14.4298
>   depth: 0.0
>   quantity: displacement
>   codes: [XS, S06D, '', T]
>   elevation: 0.0
>   store_id: PILABromanche
>   interpolation: nearest_neighbor
>   azimuth: -154.8609992983378
>   dip: 0.0
>   manual_weight: 1.0
>   analyser_results: {}
>   normalisation_family: td
>   path: td.love
>   flip_norm: false
>   misfit_config: !grond.WaveformMisfitConfig
>     fmin: 0.017
>     fmax: 0.08
>     ffactor: 1.5
>     tmin: '{stored:any_P}'
>     tmax: '{vel_surface:2.5}'
>     domain: time_domain
>     norm_exponent: 1
>     tautoshift_max: 4.0
>     autoshift_penalty_max: 0.05
> distance: 417793.4696544213
> components: [displacement.d, displacement.e, displacement.n]

Aside from the double-DC configuration options, everything else is the same as the single-source deviatoric problem which works fine. Maybe there is a subtle difference in some of the parameters between the two cases, but it is hard for me to see what is "out of range".
My config is attached.
Thanks!
[config.gronf.yaml.txt](https://github.com/pyrocko/pyrocko/files/2365611/config.gronf.yaml.txt)

**Comment by emolch** [comment]
This typically means that it is trying to use GFs that are out of the computed bounds. Either in depth or in distance. The separation of the two sources has to be taken into account for this, including all possible models in the search space. I think the parameterization of the double-dc source is not optimal - maybe we should change to absolute rather than relative coordinates, then it would be easier to set up and also more stable in the inversion.

**Comment by shicks-seismo** [comment]
Ahhhhh ok, that works now --- a little bit confusing :)
So do the initial coordinates (i.e. given by north_shift; east_shift; depth) refer to the first of the two sources?

Also, perhaps it's worth changing the "distance" argument to "delta_dist" so that it is consistent with "delta_time" and "delta_depth" ...?

**Comment by shicks-seismo** [comment]
Similar to my last question, but hopefully more understandable this time: is the first source always the largest source (assuming mix < 1), or the earliest source in time?

**Comment by emolch** [comment]
I would rather go for having absolute coordinates for both sources (or having both relative to the same origin, each with its own `north_shift` and `east_shift`, this way we would not get additional trade-offs in the parameterisation.

**Comment by emolch** [comment]
Right now, it is distributing the sources according to the mix parameter under the constraint that the centroid stays  at the same position.

It's using this source model:

* https://pyrocko.org/docs/current/library/reference/gf.html#pyrocko.gf.seismosizer.DoubleDCSource

The code is in the method `discretize_basesource` in here:

* https://pyrocko.org/docs/current/_modules/pyrocko/gf/seismosizer.html#DoubleDCSource

**Comment by emolch** [comment]
The idea was, that this way it might be possible to keep the centroid position (more or less) fixed (as determined from low frequencies, where the point source approximation is still valid).

**Comment by shicks-seismo** [comment]
Okay makes sense!
One more question - sorry for bugging you - hopefully my final request for now. 
Where can I please find the mean / best results summary.yaml files for both events. Right now, I only see one source present in the summary files.

**Comment by emolch** [comment]
Sorry, this is a bit painful at the moment. You will have to export the ensemble of solutions with
```
grond export ensemble --type=source <rundir>
```
and then analyse the resulting yaml file with a custom script. Something like this might work (*untested*):
``` python
from pyrocko import gf, guts

ddc_sources = guts.load_all(filename=sys.argv[1])
for ddc_source in ddc_sources:
    dc1, dc2 = ddc_source.split()
    # and then do stuff with the values in the two sources, e.g.:
    print(dc1.strike, dc2.strike, ...)
    # more stuff is available through the MT object you can get like this
    mt1 = dc1.pyrocko_moment_tensor()
    (strike11, dip11, rake11), (strike12, ip12, rake12) = mt1.both_strike_dip_rake()

**Comment by shicks-seismo** [comment]
Thanks, but the resulting yaml file from 
`grond export ensemble --type=source <rundir>`
only gives the solution from one source for each iteration as far as I can see right now ...

**Comment by emolch** [comment]
Could you show me a snippet of the output?

**Comment by shicks-seismo** [comment]
Something like this:

> name = e20160829.043000
> mnn = -1.09284e+19
> mee = 1.87274e+18
> mdd = 9.05562e+18
> mne = -1.10753e+19
> mnd = 7.08505e+17
> med = -7.48689e+18
> strike1 = 85.0552
> dip1 = 52.6945
> rake1 = 32.7524
> strike2 = 333.756
> dip2 = 64.5116
> rake2 = 137.824
> duration = 0
> --------------------------------------------
> name = e20160829.043000
> time = 2016-08-29 04:30:10.283
> latitude = -0.0273455715316
> longitude = -17.3489345552
> magnitude = 6.86756
> moment = 2.24565e+19
> depth = 11876.18048
> mnn = -1.09284e+19
> mee = 1.87274e+18
> mdd = 9.05562e+18
> mne = -1.10753e+19
> mnd = 7.08505e+17
> med = -7.48689e+18
> strike1 = 85.0552
> dip1 = 52.6945
> rake1 = 32.7524
> strike2 = 333.756
> dip2 = 64.5116
> rake2 = 137.824
> duration = 0
> --------------------------------------------
> name = e20160829.043000
> time = 2016-08-29 04:30:10.283
> latitude = -0.0273455715316
> longitude = -17.3489345552
> magnitude = 6.86756
> moment = 2.24565e+19
> depth = 11876.18048
> mnn = -1.09284e+19
> mee = 1.87274e+18
> mdd = 9.05562e+18
> mne = -1.10753e+19
> mnd = 7.08505e+17
> med = -7.48689e+18
> strike1 = 85.0552
> dip1 = 52.6945
> rake1 = 32.7524
> strike2 = 333.756
> dip2 = 64.5116
> rake2 = 137.824
> duration = 0

**Comment by emolch** [comment]
hmmm... this output should only come, when the option `--type=source` isn't given., maybe something in the code is wrong, I can check tomorrow.

**Comment by emolch** [comment]
It should be possible to export the DoubleDC sources with
```
grond export ensemble --type=source runs/your_run.grun > results.yaml
```

Then you can split them with the following script into individual DC sources (save as `split_ddc.py` and run as `python3 split_ddc.py results.yaml a.yaml b.yaml`):

``` python
#!/usr/bin/env python3

import sys
from pyrocko import gf, guts

if len(sys.argv) != 4:
    sys.exit('usage: split_ddc.py <input_ddcs.yaml> '
             '<output_dc_a.yaml> <output_dc_b.yaml>')

ddc_sources = guts.load_all(filename=sys.argv[1])
dc_sources_a, dc_sources_b = zip(*[s.split() for s in ddc_sources])

guts.dump_all(dc_sources_a, filename=sys.argv[2])
guts.dump_all(dc_sources_b, filename=sys.argv[3])
```

**Comment by shicks-seismo** [comment]
Super - thanks - that works great.
So this produces the ensemble of solutions. Now, what is the easiest way to now produce a summary of just the mean and best solutions only - like what `grond report` produces?

**Comment by emolch** [comment]
Instead of running
```
grond export ensemble ...
```
use
```
grond export best ...
```
or
```
grond export mean ...
```

The `split_ddc.py` should work with any of these outputs.

**Comment by shicks-seismo** [comment]
Ah that was a silly question!
Thanks a lot for your help ... excited to see the results. Will drop you a line if the double DC problem yields some robust results if you are interested.

**Comment by emolch** [comment]
Yes, I would be very interested to see your results! Thanks!

**Comment by shicks-seismo** [comment]
Hi @emolch, I tried a few runs with DoubleDCProblem and it was giving some strange results. For example, you would normally expect the overall moment to increase compared to a single source alone, even it is not a robust feature, but I found that this wasn't happening.
How is the second source being inverted for? Is it an iterative deconvolution type, whereby the synthetics from a first larger source are being deconvolved, and the remaining waveforms are then inverted for a second source?

**Comment by emolch** [comment]
No, it directly optimizes the source parameters of both sources at the same time. Only like this, it is possible to assess the uncertainties and trade-offs as a whole. Maybe a synthetic test can give some insight on when this is stable and when not. Grond has a built-in synthetic test feature which you can use for that. To activate, add a section similar to this to the `dataset_config`:
```yaml
  synthetic_test: !grond.SyntheticTest
    inject_solution: false
    respect_data_availability: false
    real_noise_scale: 0.0
    white_noise_scale: 0.0
    relative_white_noise_scale: 0.1
    random_response_scale: 0.0
    real_noise_toffset: -3600.0
    x:
      depth: 1000.0
      duration: 1.0
      east_shift: 0.0
      magnitude: 4.5
      north_shift: 0.0
      rmdd: -1.0
      rmed: 0.0
      rmee: -0.33
      rmnd: 0.0
      rmne: 0.0
      rmnn: -0.33
      time: 0.0
```
The parameters given, define the "true" model (takes the same parameters as in the `problem_config.ranges`).

I always wanted to run a series of synthetic tests like this for the double-dc source, to find out what the minimal separation of the two sources is in order to make the problem stable. But I didn't find time to that...

**Comment by braunfuss** [comment]
As for the moment: only a single moment is optimized for but then distributed between the two sources according to the parameter mix. Therefore the moment does not necessarily need to be larger then for a single DC, i even expect it to be a bit smaller, if tdiff between the source is rather small. I have run several synthetic tests and runs on real data that also will be shown in an upcoming paper (hopefully soon). I found that the minimum spatial separation distance is dependent on the temporal separation between the sources. In general i would recommend that the spatial separation however is around one wavelength minimum.
