### ISSUE TITLE
minimizer / Hdf5 error

### ISSUE THREAD

**Issue by RedouaneNouh** [pyrocko/pyrocko#300]
Hello, please any idea how to deal with this issue? I'm using rapidinv, kiwi tools
Thank you.
whene I run the rapidinv, with one exemple input I get:
minimizer: something went wrong in minimize_lm
STOP 1
Analysing results inversion step 1...
50 0
ERROR 1: n start sol <> n point sol (minimizer.out)

with another input file, that seams to be well adjusted I get this:
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5A.c line 567 in H5Aopen_by_idx(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: H5Gloc.c line 251 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5A.c line 728 in H5Aget_space(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5S.c line 758 in H5Sget_simple_extent_npoints(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.1) thread 0:
  #000: H5S.c line 431 in H5Sclose(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
minimizer: gfdb: failed to get size of attributes of a dataset
STOP 1
Analysing results inversion step 1...
50 0
ERROR 1: n start sol <> n point sol (minimizer.out)

**Comment by RedouaneNouh** [comment]
Any Idea?

**Comment by emolch** [comment]
Hi,
the problem is, that the Kiwi Tools are incompatible with HDF Version 1.10. You should install version 1.8 of HDF5. We have added a script `get_hdf5_18.sh` which should download and compile HDF5 version 1.8 for static linkage locally. After running, it reports some variables which should be added to `Makefile.local`.

**Comment by RedouaneNouh** [comment]
Hi, 
thank you for your response, 
but, would you please indicate where to find that script get_hdf5_18.sh ? cause I'm totally lost

**Comment by hvasbath** [comment]
https://github.com/emolch/kiwi/get_hdf5_18.sh

**Comment by RedouaneNouh** [comment]
Hi sir, 
the link returns : Not Found

**Comment by hvasbath** [comment]
https://github.com/emolch/kiwi/blob/master/get_hdf5_18.sh

**Comment by RedouaneNouh** [comment]
Thank you very much
have a nice day
