### ISSUE TITLE
Cake phase custom model

### ISSUE THREAD

**Issue by shicks-seismo** [pyrocko/pyrocko#303]
What format does the velocity model need to be in when importing a custom model into Cake Phase using the `Add Model` button? I tried using a .nd file, but this doesn't work, so I assume that the nd model needs first be loaded as a builtin velocity model?

**Comment by emolch** [comment]
Reading of custom nd models usually works. What error message is printed? Could please post the file?

**Comment by shicks-seismo** [comment]
Here is the error:

> (pyrocko) 154-28:raw sph1r17$ snuffler *00* --event=../../event.txt --stationxml="../../../metadata/*"
> objc[94956]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8655fc90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1c3a0cacd8). One of the two will be used. Which one is undefined.
> Traceback (most recent call last):
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gui/snuffling.py", line 1201, in f
>     method()
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gui/snufflings/cake_phase.py", line 190, in add_model_to_choice
>     in_model = self.input_filename('Load Model')
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gui/snuffling.py", line 1323, in input_filename
>     filter)  # selected_filter)
> ValueError: too many values to unpack (expected 2)

Attached is the velocity model file. I tried it with and without the id label in case that was needed, but got the same error in each case.
[model.nd.txt](https://github.com/pyrocko/pyrocko/files/2404779/model.nd.txt)

**Comment by shicks-seismo** [comment]
Thanks, @miili, but that didn't quite fix the problem. Do I need the ID label at the top of the file?

**Comment by braunfuss** [comment]
hey @shicks-seismo:
The first line is not necessary and the layer indicator 'mantel' need to be not indented. 
Here i attached it, where it can be load in cake with:
model = cake.load_model('model.nd.txt')
[model.nd.txt](https://github.com/pyrocko/pyrocko/files/2410113/model.nd.txt)

**Comment by shicks-seismo** [comment]
Many thanks, @braunfuss; however, I still get an error when loading your model into Snuffler (via the Cake Phase) snuffling panel.

> (pyrocko) NOCS04167J-2:waveforms sph1r17$ snuffler --event=../event.txt --stationxml=all_XS_4_elev-4000.xml raw/*
> objc[76903]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8655fc90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1c30101cd8). One of the two will be used. Which one is undefined.
> Traceback (most recent call last):
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gui/snuffling.py", line 1201, in f
>     method()
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gui/snufflings/cake_phase.py", line 190, in add_model_to_choice
>     in_model = self.input_filename('Load Model')
>   File "/Users/sph1r17/anaconda/envs/pyrocko/lib/python3.6/site-packages/pyrocko/gui/snuffling.py", line 1323, in input_filename
>     filter)  # selected_filter)
> ValueError: too many values to unpack (expected 2)

**Comment by braunfuss** [comment]
That is due to a bug that was fixed in a release 3 months ago, please update your pyrocko installation, that should fix it.

**Comment by miili** [comment]
@shicks-seismo let us know when you got it working.

**Comment by shicks-seismo** [comment]
Yep, all fixed now after updating from source. Thanks again!

**Comment by miili** [comment]
Excellent
