### ISSUE TITLE
TypeA stores and check_rect_source_discretisation

### ISSUE THREAD

**Issue by braunfuss** [pyrocko/pyrocko#314]
In https://github.com/pyrocko/pyrocko/commit/7ca5701c50b4dde7b239b3854341c1a2db5e0f1f
the discretisation check was introduced. This renders all TypeA stores unable to be used with rectangular sources, as they do not have the `get_vs()`.
Is this intended as such? 
https://github.com/pyrocko/pyrocko/blob/a2414edaedf602b3d3372c1b12eaebe1872bb701/src/gf/seismosizer.py#L239

**Comment by hvasbath** [comment]
This method is defined at the Config class. Config Type A inherits from that, so it should have it as well. DId you test it? There must be sth fishy going on if it fails.

**Comment by braunfuss** [comment]
File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 1788, in _discretize
    if not check_rect_source_discretisation(points, nl, nw, store):
yes this would be the error:  
File "/usr/local/lib/python3.5/dist-packages/pyrocko/gf/seismosizer.py", line 239, in check_rect_source_discretisation
    vs_profile = store.config.get_vs(
AttributeError: 'ConfigTypeA' object has no attribute 'get_vs'

**Comment by hvasbath** [comment]
Yes I think that the old dumped configs are not updated automatically during loading through guts? But I am not sure? @emolch

**Comment by emolch** [comment]
That cannot be the cause. Method names are never dumped.

**Comment by braunfuss** [comment]
Seems to be an installation issue on my side, sorry! (meta.py was not updated for some reason in /usr/local/lib/)
