### ISSUE TITLE
Error when running beat sample Laquila --hypers

### ISSUE THREAD

**Issue by vic-chou** [pyrocko/pyrocko#329]
Hi,  when I running "beat sample Laquila --hypers" following Scenario I, I meet a error said
 "AttributeError: Can't get attribute 'Quadtree' on <module 'beat.heart' from '/usr/local/lib/python3.4/dist-packages/beat-1.0rc1-py3.4-linux-x86_64.egg/beat/heart.py'>". 
Can you help me solve this problem?

**Comment by hvasbath** [comment]
I re-opened the issue here: https://github.com/hvasbath/beat/issues/20
Please use this top for BEAT related issues! Thanks!
