### ISSUE TITLE
Downgrade to python2

### ISSUE THREAD

**Issue by zackspica** [pyrocko/pyrocko#333]
Hi Sebastian et al.,

I am trying to move to python 3 and installed Anaconda 3. 
At the time of doing "conda install -c pyrocko pyrocko", it requires me to DOWNGRADE to python 2...
Any suggestion? 

Thanks

------------------------------------------------

The following packages will be DOWNGRADED:

    anaconda-client:                    1.7.2-py37_0                          --> 1.7.1-py_0               conda-forge
    appscript:                          1.0.1-py37h1de35cc_1                  --> 1.0.1-py27h470a237_0     conda-forge
    astroid:                            2.0.4-py37_0                          --> 1.6.5-py27_0             conda-forge
    fastcache:                          1.0.2-py37h1de35cc_2                  --> 1.0.2-py27h470a237_1     conda-forge
    greenlet:                           0.4.15-py37h1de35cc_0                 --> 0.4.13-py27_0            conda-forge
    hyperlink:                          18.0.0-py37_0                         --> 17.3.1-py_0              conda-forge
    ipython:                            6.5.0-py37_0                          --> 5.8.0-py27_0             conda-forge
    jupyter:                            1.0.0-py37_7                          --> 1.0.0-py_1               conda-forge
    jupyterlab:                         0.34.9-py37_0                         --> 0.33.12-py27_0           conda-forge
    jupyterlab_launcher:                0.13.1-py37_0                         --> 0.11.2-py_0              conda-forge
    lazy-object-proxy:                  1.3.1-py37h1de35cc_2                  --> 1.3.1-py27h470a237_0     conda-forge
    mpmath:                             1.0.0-py37_2                          --> 1.0.0-py_1               conda-forge
    nltk:                               3.3.0-py37_0                          --> 3.2.4-py27_0             conda-forge
    numpy:                              1.15.1-py37h6a91979_0                 --> 1.10.2-py27_0                       
    pyasn1-modules:                     0.2.2-py37_0                          --> 0.2.1-py_0               conda-forge
    pycrypto:                           2.6.1-py37h1de35cc_9                  --> 2.6.1-py27h470a237_2     conda-forge
    pylint:                             2.1.1-py37_0                          --> 1.9.2-py27_0             conda-forge
    python:                             3.7.0-hc167b69_0                      --> 2.7.15-h43f7c74_0        conda-forge
    python.app:                         2-py37_8                              --> 1.2-py27_200             conda-forge
    rope:                               0.11.0-py37_0                         --> 0.10.7-py_1              conda-forge
    scipy:                              1.1.0-py37h28f7352_1                  --> 0.16.0-np110py27_1                  
    simplegeneric:                      0.8.1-py37_2                          --> 0.8.1-py_1               conda-forge
    spyder:                             3.3.1-py37_1                          --> 3.2.8-py27_0             conda-forge
    wrapt:                              1.10.11-py37h1de35cc_2                --> 1.10.11-py27h470a237_1   conda-forge

Proceed ([y]/n)? n

**Comment by zackspica** [comment]
Ok, there is a non-linear behavior I don't understand but it is now solved. I installed other packages using conda and then came back to the pyrocko installation. Now it downgrades from py3.7 to py 3.6, which is fine for me. 

--------

python:                             3.7.0-hc167b69_0                      --> 3.6.6-h5001a0f_0         conda-forge

**Comment by hvasbath** [comment]
We have few packages for non-linear optimizations that could help you to find the global minimum :smile: .

**Comment by HerrMuellerluedenscheid** [comment]
Hi @zackspica, 

Thanks for sharing that. I think that we can close the issue, right? If there is need for further support feel free to drop us another question or to re-open this issue.
Have a nice day
Marius
