### ISSUE TITLE
Problems with fresh installation

### ISSUE THREAD

**Issue by jeffersonite** [pyrocko/pyrocko#334]
I have a fresh CentOS 7 (3.10.0-957.1.3.el7.x86_64) GNOME VM on VMware.
Installed GMT through `yum` per their instructions.

Installed pyrocko either from source, or using `pip`. Testing out some of the example files, and got this error:
```
$ python pyrocko/examples/automap_example.py 
Traceback (most recent call last):
  File "pyrocko/examples/automap_example.py", line 91, in <module>
    m.save('automap_deadsea.png')
  File "/usr/lib64/python2.7/site-packages/pyrocko/plot/automap.py", line 223, in save
    size=size, width=width, height=height)
  File "/usr/lib64/python2.7/site-packages/pyrocko/plot/gmtpy.py", line 3648, in save
    size=size, width=width, height=height)
  File "/usr/lib64/python2.7/site-packages/pyrocko/plot/gmtpy.py", line 128, in convert_graph
    'Cannot start `convert`, is it installed? (%s)' % str(e))
pyrocko.plot.gmtpy.GmtPyError: Cannot start `convert`, is it installed? ([Errno 2] No such file or directory)
```
Changed the suffix from `png` to `pdf` and the script ran fine.

Don't know if they are related, but there is this cryptic message from another example:
```
$ python pyrocko/examples/topo_example.py 
Unable to parse the pattern
```
The other examples seem to run fine (after fixing minor typos in the script), but these two do not make sense. I installed pyrocko on a different VM a couple weeks ago, and `automap_example.py` and `topo_example.py` ran fine.

**Comment by miili** [comment]
Hi Jefferson,

`convert` is part of the software package ImageMagick. If you need the conversion install it on the CentOS machine with yum.

Regarding your issue with the topo example, which python version are you running? `python --version`
