### ISSUE TITLE
`util.progressbar`

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [pyrocko/pyrocko#345]
`util.progressbar` instances do not update properly when progressbar2 package is installed.

**Comment by HerrMuellerluedenscheid** [comment]
This is an issue related to the version of progressbar2. v3.38.0 updates fine, while v3.39.0 doesn't

**Comment by HerrMuellerluedenscheid** [comment]
solved in 9ad1dc76f05016e4e22daf18e89b987191ae5f37

**Comment by emolch** [comment]
:+1:
