### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by brioglade** [pyrocko/pyrocko#353]
in ubuntu : conda install -c pyrocko pyrocko
    PermissionError: [Errno 13] Permission denied: '/home/ufo/anaconda3/.condatmp'

**Comment by emolch** [comment]
Looks like a file permission problem. Maybe because of some previous use of `sudo` when installing somithing. `sudo` should be avoided when working with anaconda. Does the `anaconda3` directory belong to `ufo`?

**Comment by brioglade** [comment]
I used to install python-numpy python-matplotplt with sudo.
The anaconda3 directory belong to /home.
the same error occur when I update Conda using conda update -n base -c defaults conda.
So what can I do?
Thank u ! @emolch

**Comment by emolch** [comment]
See if owner of files in `~/anaconda3` is `ufo`:
```
ls -la ~/anaconda3
```

**Comment by brioglade** [comment]
ufo@doughnut:~$ ls -la ~/anaconda3
total 212
drwxr-xr-x  23 root root  4096 1月   4 14:51 .
drwxr-xr-x  40 ufo  ufo   4096 3月  20 17:09 ..
drwxr-xr-x   2 root root 12288 1月   4 14:51 bin
drwxr-xr-x   2 root root  4096 1月   4 14:48 compiler_compat

**Comment by emolch** [comment]
That's the problem: `anaconda3` folder belongs to root. Try to fix things with
```
sudo chown -R ufo.ufo ~/anaconda3/
```
or if things are already screwed up too much, try a fresh install of anaconda.

**Comment by brioglade** [comment]
Is the following command avoided?
sudo apt install python-numpy 
This command seems installing python-numpy package in ubuntu system based python2.
Did this command  screw up anaconda3?

**Comment by emolch** [comment]
No these are completely separate worlds. The system package manager won't do anything in your user anaconda installation.

**Comment by brioglade** [comment]
But I can not open spyder in terminal without sudo installation.

**Comment by brioglade** [comment]
OK,I got it.
Thank you very much.

**Comment by hvasbath** [comment]
Seems resolved. Closing now. Please reopen if further questions arise.
