### ISSUE TITLE
polarity in Quakeml and Phasemarker of different type

### ISSUE THREAD

**Issue by marzeck** [pyrocko/pyrocko#354]
Hi guys,
I'm really glad, that there is a native function for translating a Quakeml-class Pick into a pyrocko Phasemarker. Unfortunately there is a small bug with the polarity, because Quakeml wants this attribute to be a string:
` Any ``str`` out of ``['positive', 'negative', 'undecidable']``.`
And the Phasemarker one of the following:
` polarity has to be 1, -1, 0 or None`

Maybe you could fix this, as you can't call the polarity attribute directly from each others class.
Cheers,
marzeck

**Comment by HerrMuellerluedenscheid** [comment]
Hi Martin,

Please update pyrocko. It should work now (see 6a1368405c225855941546148ae6cc6ff607540f)
