### ISSUE TITLE
Synthetic seismogram created by Fomosto, how to save it to mseed file?

### ISSUE THREAD

**Issue by rexhavry** [pyrocko/pyrocko#361]
Hi, I just recently use Pyrocko and Fomosto for my study.
I used Fomosto to generate Green Function based on certain velocity model. Then, fomosto report could nicely produced Synthetic Displacement Seismogram when I put certain souce parameter (distance,dip,strike,rake,azimuth etc).
What I need to do next, is to analyze this synthetic seismogram which I have generated. How can I extract the data in Python? or put it simply, how can I export it to mseed?

Please, your help is required
Thank you.

**Comment by hvasbath** [comment]
Hi,

once you calculated your seismograms following this example:
https://pyrocko.org/docs/current/library/examples/gf_forward.html#calculate-synthetic-seismograms-from-a-local-gf-store

You can store the output synthetic traces following this example:
```
from pyrocko import io
outputpath = '/please/specify/the/absolut/path/to/your/save-directory/outtraces.mseed'
io.save(synthetic_traces, outputpath, format='mseed')
```

**Comment by rexhavry** [comment]
Hi Hvasbath

Thank you so much, it works.
