### ISSUE TITLE
Stations load in contributing snufflings. 

### ISSUE THREAD

**Issue by zackspica** [pyrocko/pyrocko#367]
Hi there, 

How is the station information loaded in the contributing snufflings?

Z.

**Comment by braunfuss** [comment]
Hi, i think you want how it is done practically in the code? self.get_active_event_and_stations() does the job. For more fallbacks and alternatives have a look at the station map snufflings code:
https://github.com/pyrocko/pyrocko/blob/0840f3714518f9497574c3da01c2002636d085b5/src/gui/snufflings/map/__init__.py#L204 L204-L248.

**Comment by zackspica** [comment]
Oh nice, so there is a --stations=stations_filename argument :)
Thanks

**Comment by braunfuss** [comment]
Yes the user can load in the stations file with the dialog in the snuffler or with this argument added to the cmd line call of snuffler.

**Comment by hvasbath** [comment]
Actually the argument in the options would be --stations not stations_filename. See snuffler --help.
