### ISSUE TITLE
Extend Markers in the way that e.g. polarities can be assigned

### ISSUE THREAD

**Issue by HerrMuellerluedenscheid** [pyrocko/pyrocko#42]

**Comment by miili** [comment]
@HerrMuellerluedenscheid is this feature now implemented?

**Comment by HerrMuellerluedenscheid** [comment]
No, unfortunately not. This requires some changes in the design of `PhaseMarker` in `gui_util.py` and to adapt `marker_editor.py` to those changes. There needs to be a nice way to indicate selected polarities in the viewer (little arrow maybe?) while keeping it visually lightweight. Or would it be enough to show the polarity in the marker table? I think this feature would be very beneficial for many people using snuffler for picking phases. Despite the assignment of polarities we should thing about other meta information options which should be added. E.g. quality of a picked phase is often used for weighting picks. Phase kinds can be assigned by pressing numbers 0-5 but these are already used by other snufflings and applications. Hence, another table row for pick quality? Is the then still flexibly enough?

If markers were saved and loaded using yaml one could imagine a right click option in the marker editor to create meta data fields to be attached to a `Marker`. These could be defined by the user but I am not sure if we should allow this. Could cause many unforeseeable problems when the editors` columns change depending on the loaded catalogue.
Maybe a dedicated `picking-snuffling` would be best with a dedicated `PhasePickMarker` subclass of `PhaseMarker` which can be modified by users to meet their needs. 

There is another thing which should be done once we touch this issue. `EventMarkers` are representatives for `model.Event` instances. `PhaseMarkers` should have an equivalent, e.g. `model.Ray`.
Any opinions?

**Comment by HerrMuellerluedenscheid** [comment]
Polarities can be assigned using up/down arrows.
